SYMBOLS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
encrypted = "PJY A OWCLO"
secret = "INTROAYYMANTURNONTHATBEATDAWGTHEONETHATIMADEUHMINUTESAGOHEHEHTHISBITCHHARDASFUCKDAMNALRIGHTCHORUSALLTHESEWEBSONMEYOUTHINKIMSPIDERMANALLTHESEWEBSONMEYOUTHINKIMSPIDERMANALLTHESEWEBSONMEYOUTHINKIMSPIDERMANALLTHESEWEBSONMEYOUTHINKIMSPIDERMANALLTHESEWEBSONMEYOU"

def vernam_encrypt(message, key):
    res = []
    for i in range(len(message)):
        indMsg = SYMBOLS.find(message[i])
        indKey = SYMBOLS.find(key[i])
        resInd = (indMsg ^ indKey) % len(SYMBOLS)
        res.append(SYMBOLS[resInd])

    return ''.join(res)

print(vernam_encrypt(encrypted, secret))